name: Check Types with mypy

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry" # caching pip dependencies
      - run: poetry install
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install poetry
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Run mypy
        run: poetry run mypy .
