name: Check Types with mypy

on: [push, pull_request]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Adjust the Python version as needed

      # Cache Poetry dependencies
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      # Install Poetry
      - name: Install Poetry
        run: |
          run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath --global
          pipx install poetry
          poetry completions bash >> ~/.bash_completion
          poetry lock --no-update

      # Install dependencies using Poetry
      - name: Install dependencies
        run: poetry install

      # Cache virtual environment
      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-

      # Run type checking with mypy
      - name: Run mypy
        run: poetry run mypy .
